sudo: required
language: ruby
env:
  global:
    - IMAGE_NAME=tugrulelmas/abioka-com
addons:
  apt:
    packages:
      - docker-ce
  ssh_known_hosts: ec2-35-177-32-171.eu-west-2.compute.amazonaws.com
services:
  - docker
  
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a18ef0598_key -iv $encrypted_b06a18ef0598_iv -in abioka-linux2.pem.enc -out abioka-linux2.pem -d
  - rm abioka-linux2.pem.enc
  - chmod 400 abioka-linux2.pem

script:
  - docker build -t "$IMAGE_NAME":latest -t "$IMAGE_NAME":"$TRAVIS_COMMIT" .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$IMAGE_NAME":"$TRAVIS_COMMIT";
    docker push "$IMAGE_NAME":latest;
    sed -i 's/${ABIOKA_TAG}/' >> "$TRAVIS_COMMIT" >>'/g' docker-compose.yml
    scp -i abioka-linux2.pem docker-compose.yml ubuntu@ec2-35-177-32-171.eu-west-2.compute.amazonaws.com:~;
    bash deploy.sh;
    fi
