sudo: required
language: ruby
addons:
  apt:
    packages:
      - docker-ce
  ssh_known_hosts: ec2-35-158-221-148.eu-central-1.compute.amazonaws.com
services:
  - docker
  
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a18ef0598_key -iv $encrypted_b06a18ef0598_iv
    -in abioka-linux.pem.enc -out abioka-linux.pem -d
  - rm abioka-linux.pem.enc # Don't need it anymore
  - chmod 400 abioka-linux.pem

script:
  - docker build -t tugrulelmas/abioka-com:latest -t tugrulelmas/abioka-com:$TRAVIS_COMMIT .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tugrulelmas/abioka-com:$TRAVIS_COMMIT;
    docker push tugrulelmas/abioka-com:latest;
    sed -i 's/${ABIOKA_TAG}/' >> "$TRAVIS_COMMIT" >>'/g' docker-compose.yml
    scp -i "abioka-linux.pem" docker-compose.yml ec2-user@ec2-35-158-221-148.eu-central-1.compute.amazonaws.com:~;
    bash deploy.sh "$TRAVIS_COMMIT";
    fi
