sudo: required
language: ruby
env:
  - RemoteHost=ec2-35-158-221-148.eu-central-1.compute.amazonaws.com
  - RemoteUser=ec2-user
  - ImageName=tugrulelmas/abioka-com
  - SSHKey=abioka-linux.pem
addons:
  apt:
    packages:
      - docker-ce
  ssh_known_hosts: $RemoteHost
services:
  - docker
  
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a18ef0598_key -iv $encrypted_b06a18ef0598_iv
    -in "$SSHKey" >> '.enc' -out $SSHKey -d
  - rm "$SSHKey" >> '.enc'
  - chmod 400 $SSHKey

script:
  - docker build -t $ImageName:latest -t $ImageName:$TRAVIS_COMMIT .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $ImageName:$TRAVIS_COMMIT;
    docker push $ImageName:latest;
    sed -i 's/${ABIOKA_TAG}/' >> "$TRAVIS_COMMIT" >>'/g' docker-compose.yml
    scp -i "$SSHKey" docker-compose.yml $RemoteUser@$RemoteHost:~;
    bash deploy.sh "$TRAVIS_COMMIT";
    fi
