sudo: required
language: ruby
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
  
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a18ef0598_key -iv $encrypted_b06a18ef0598_iv
    -in abioka-linux.pem.enc -out abioka-linux.pem -d
  - rm abioka-linux.pem.enc # Don't need it anymore
  - chmod 600 abioka-linux.pem

script:
  - docker build -t tugrulelmas/abioka-com .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tugrulelmas/abioka-com;
    ssh -i "abioka-linux.pem" ec2-user@ec2-35-158-221-148.eu-central-1.compute.amazonaws.com
    docker run --name abioka -d -p 80:80 tugrulelmas/abioka-com
    fi
