version: '3'
services:
  app:
    image: tugrulelmas/abioka-com
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=abioka.com
      - NGINX_PORT=80
    networks:
      - webnet
networks:
  webnet:
