name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        BUILD_SCRIPT: |
          npm install gulp-cli -g 
          npm install
          gulp
          mkdir dist && cp -avr img/ dist/img/ && cp -avr css/ dist/css/ && cp -avr js/ dist/js/ && cp index.html dist/
